on:
  workflow_dispatch:

jobs:
  bisect:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout mysql-server
        uses: actions/checkout@v4
        with:
          repository: mysql/mysql-server
          path: mysql-server
          ref: mysql-8.0.32
          fetch-depth: 0
      - run: setup.ps1
      - run: bisect.ps1
