on:
  workflow_dispatch:

jobs:
  bisect:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: mxschmitt/action-tmate@v3
      - run: .\bisect.ps1
